# Generated by Django 5.1.2 on 2024-10-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('auther', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='books/images')),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='borrower')),
            ],
        ),
    ]
